### ISSUE TITLE
error while creating hitboxes blender 3.0.0

### ISSUE THREAD

**Issue by lorsange** [xbodya13/ragdoll_tools_doc#11]
When trying choose "bones" instead of "Mesh" during creating hitboxes always get error in 2706 line of "ragdoll_tools_1_4_3.py"

Python: Traceback (most recent call last):
File "C:\Users\.........\AppData\Roaming Blender Foundation Blender 3.0\scripts/addons\ragdoll_tools_1_4_3.py", line 3240, in execute mesh = self.capsule_mesh(pose_bone.bone,matrix)
File "C:\Users\.........\AppData\Roaming Blender Foundation Blender/3.0\scripts\addons/ragdoll_tools_1_4_3.py", line 2706, in capsule_mesh head sphere = bmesh.ops.create_uvsphere(bm, u segments=u_segments, v_segments=v_segments, diameter-head_radius)

TypeError. create_uvsphere: keyword "diameter" is invalid for this operator

location: <unknown location>:-1

**Comment by xbodya13** [comment]
Hi.
Try ragdoll_tools_1_4_5.py
