### ISSUE TITLE
Not available in 2.90

### ISSUE THREAD

**Issue by Hammers69** [xbodya13/ragdoll_tools_doc#3]
Hi I've just bought the addon on Blendermarket. It looks great, and I'm hoping will streamline a rigid body situation I'm trying.

I am currently adopting 2.90 for my workflow. Early I know, so I was wondering if you have plans to make the addon compatible. At the moment it installs but doesn't show in the search function. Fine in 2.83.

Thanks!

**Comment by xbodya13** [comment]
Hi.
Yes,i'll update the addon to 2.9 once it becomes more stable.

**Comment by mysticfall** [comment]
Version 1.4 still fails with 2.9x:

```
module changed on disk: '/home/mysticfall/.config/upbge/2.93/scripts/addons/ragdoll_tools_1_4_2.py' reloading...
Traceback (most recent call last):
  File "/usr/share/upbge/2.93/scripts/modules/addon_utils.py", line 330, in enable
    importlib.reload(mod)
  File "/usr/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/mysticfall/.config/upbge/2.93/scripts/addons/ragdoll_tools_1_4_2.py", line 1951, in <module>
    class SetRBCSettings(bpy.types.Operator):
  File "/home/mysticfall/.config/upbge/2.93/scripts/addons/ragdoll_tools_1_4_2.py", line 1958, in SetRBCSettings
    class object(bpy.types.PropertyGroup):
  File "/home/mysticfall/.config/upbge/2.93/scripts/addons/ragdoll_tools_1_4_2.py", line 1960, in object
    class rigid_body_constraint(bpy.types.PropertyGroup): pass
  File "/home/mysticfall/.config/upbge/2.93/scripts/addons/ragdoll_tools_1_4_2.py", line 899, in pgroup_from_type_inner
    c_object.__annotations__[p_name]=prop_from_type(p_type, **override[p_name])
  File "/home/mysticfall/.config/upbge/2.93/scripts/addons/ragdoll_tools_1_4_2.py", line 885, in prop_from_type
    if key in out[1].keys():
TypeError: '_PropertyDeferred' object is not subscriptable
```

**Comment by xbodya13** [comment]
Hi.
What exact version of blender are you using?

**Comment by mysticfall** [comment]
Hi, I'm using the latest version of the master branch.

**Comment by xbodya13** [comment]
Do you mean 2.93 (258b15da74ad) ?
If yes,try 2.92 instead,2.93 is still an alpha

**Comment by mysticfall** [comment]
Sorry, I need the up-to-date version of UPBGE (bfa2cbbc4) for my project which is built on the latest Blender, so I can't downgrade.

It looks like the code assumes that `bpy.props.*Property` defines `__getitem__` which seems to be no longer the case with 2.93+. Not sure what it means to access a property with an index, however.

**Comment by xbodya13** [comment]
bpy.props.*Property() returned a tuple since 2.79...now it returns something else.
I hoped to find a quick fix for that, but current 2.93 build is missing api-ms-win-core-path-l1-1-0.dll

**Comment by xbodya13** [comment]
Version 1.4.3 is now working with 2.93
Sorry for such a long wait,i had to switch to linux
