### ISSUE TITLE
Error when trying to install addon

### ISSUE THREAD

**Issue by Sparkie1j** [xbodya13/ragdoll_tools_doc#8]
I get this error when i hit the check box to install the addon. it wont let me use it
Traceback (most recent call last):
  File "F:\SteamLibrary\steamapps\common\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Jared\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\ragdoll_tools_1_4_2.py", line 1951, in <module>
    class SetRBCSettings(bpy.types.Operator):
  File "C:\Users\Jared\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\ragdoll_tools_1_4_2.py", line 1958, in SetRBCSettings
    class object(bpy.types.PropertyGroup):
  File "C:\Users\Jared\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\ragdoll_tools_1_4_2.py", line 1960, in object
    class rigid_body_constraint(bpy.types.PropertyGroup): pass
  File "C:\Users\Jared\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\ragdoll_tools_1_4_2.py", line 899, in pgroup_from_type_inner
    c_object.__annotations__[p_name]=prop_from_type(p_type, **override[p_name])
  File "C:\Users\Jared\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\ragdoll_tools_1_4_2.py", line 885, in prop_from_type
    if key in out[1].keys():
TypeError: '_PropertyDeferred' object is not subscriptable

**Comment by xbodya13** [comment]
Hi.
Try the latest 1.4.3 version
